apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kuard
  namespace: kuard
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    kind: Deployment
    name: kuard
  targetCPUUtilizationPercentage: 30
